"""add_agent_secret_to_tenants

Revision ID: f4f65b63ad7f
Revises: 002_add_documents
Create Date: 2026-03-24 18:50:48.648178

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f4f65b63ad7f'
down_revision: Union[str, Sequence[str], None] = '002_add_documents'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('agent_secret', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenants', 'agent_secret')
    # ### end Alembic commands ###
